export const ADD_MOVIES_TO_WATCHLIST = "ADD_MOVIES_TO_WATCHLIST";
export const REMOVE_MOVIES_FROM_WATCHLIST = "REMOVE_MOVIES_FROM_WATCHLIST";
export const ADD_MOVIES_TO_WATCHED = "ADD_MOVIES_TO_WATCHED";
export const REMOVE_MOVIES_FROM_WATCHED = "REMOVE_MOVIES_FROM_WATCHED";
export const MOVE_TO_WATCHLIST = "MOVE_TO_WATCHLIST";
